fix: Still debugging mysql for gh-action

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -109,9 +109,7 @@ jobs:
               run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
 
             - name: Run Migration
-              run: |
-                  php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
-                  php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+              run: php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
               env:
                   DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
 
@@ -133,3 +131,5 @@ jobs:
 
             - name: Execute tests via PHPUnit
               run: vendor/bin/phpunit
+              env:
+                  DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
