github: Added mysql to actions for tests

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -8,12 +8,19 @@ on:
 
 jobs:
     static-analysis:
+        name: Static Analysis (PHP ${{ matrix.php-versions }})
         runs-on: ubuntu-latest
+        strategy:
+            fail-fast: false
+            matrix:
+                php-versions: ["8.0", "8.1"]
         steps:
+            - name: Checkout
+              uses: actions/checkout@v2
+
             - uses: shivammathur/setup-php@v2
               with:
-                  php-version: "8.0"
-            - uses: actions/checkout@v2
+                  php-version: ${{ matrix.php-versions }}
 
             - name: Copy .env.test.local
               run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
@@ -62,12 +69,31 @@ jobs:
               run: yarn run prettier --check .
 
     tests:
+        name: Tests (PHP ${{ matrix.php-versions }})
         runs-on: ubuntu-latest
+        services:
+            mysql:
+                image: mysql:latest
+                env:
+                    MYSQL_ALLOW_EMPTY_PASSWORD: false
+                    MYSQL_ROOT_PASSWORD: symfony
+                    MYSQL_DATABASE: symfony
+                ports:
+                    - 3306/tcp
+        strategy:
+            fail-fast: false
+            matrix:
+                php-versions: ["8.0", "8.1"]
         steps:
+            - name: Checkout
+              uses: actions/checkout@v2
+
             - uses: shivammathur/setup-php@v2
               with:
-                  php-version: "8.0"
-            - uses: actions/checkout@v2
+                  php-version: ${{ matrix.php-versions }}
+
+            - name: Start mysql service
+              run: sudo systemctl start mysql
 
             - name: Copy .env.test.local
               run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
@@ -80,8 +106,17 @@ jobs:
                   key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                   restore-keys: |
                       ${{ runner.os }}-php-
+
             - name: Install Dependencies
               run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
+
+            - name: Run Migration
+              run: |
+                  composer require --dev symfony/orm-pack
+                  php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+                  php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+              env:
+                  DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
 
             - name: Cache node_modules
               uses: actions/cache@v1
