Improving tests (#825)
* feat: Added doctrine-test-bundle

* fix: Replaced deprecated storage_id

* feat: Added GlobalStory for Application tests

* test: Added Test for public/secure Urls

* fix: Restricting access to ROLE_USER

* style: PHP-CS-Fixer

* style: Ignoring /bin

* tests: Improved Coverage

* tests: Improved Coverage& fixed ArrayCollection

Also finally added Imports to Interface!

* tests: Added missing /Domain/Entity tests

* build: Added zenstruck/browser

* tests: Added first Demo test

* github: Added mysql to actions for tests

* fix: Improving github action& mysql

* fix: Updated mysql config, will it work?

* github: Debugging mysql action for tests

* fix: Still debugging mysql for gh-action

* fix: Another try to fix mysql

* fix: Updated action and removed --force

* Still debugging Browser test

* Yet still debugging the same issue

* Issue fixed trough setting the locale?

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -8,12 +8,19 @@ on:
 
 jobs:
     static-analysis:
+        name: Static Analysis (PHP ${{ matrix.php-versions }})
         runs-on: ubuntu-latest
+        strategy:
+            fail-fast: false
+            matrix:
+                php-versions: ["8.0", "8.1"]
         steps:
+            - name: Checkout
+              uses: actions/checkout@v2
+
             - uses: shivammathur/setup-php@v2
               with:
-                  php-version: "8.0"
-            - uses: actions/checkout@v2
+                  php-version: ${{ matrix.php-versions }}
 
             - name: Copy .env.test.local
               run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
@@ -62,15 +69,32 @@ jobs:
               run: yarn run prettier --check .
 
     tests:
+        name: Tests (PHP ${{ matrix.php-versions }})
         runs-on: ubuntu-latest
+        services:
+            mysql:
+                image: mysql:latest
+                env:
+                    MYSQL_ALLOW_EMPTY_PASSWORD: false
+                    MYSQL_ROOT_PASSWORD: symfony
+                    MYSQL_DATABASE: symfony
+                ports:
+                    - 3306/tcp
+                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+        strategy:
+            fail-fast: false
+            matrix:
+                php-versions: ["8.0", "8.1"]
         steps:
+            - name: Checkout
+              uses: actions/checkout@v2
+
             - uses: shivammathur/setup-php@v2
               with:
-                  php-version: "8.0"
-            - uses: actions/checkout@v2
+                  php-version: ${{ matrix.php-versions }}
 
             - name: Copy .env.test.local
-              run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
+              run: php -r "file_exists('.env.test.local') || copy('.env.github.test', '.env.test.local');"
 
             - name: Cache Composer packages
               id: composer-cache
@@ -80,8 +104,14 @@ jobs:
                   key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                   restore-keys: |
                       ${{ runner.os }}-php-
+
             - name: Install Dependencies
               run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
+
+            - name: Run Migration
+              run: php bin/console doctrine:schema:create || echo "No schema found or schema failed"
+              env:
+                  DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
 
             - name: Cache node_modules
               uses: actions/cache@v1
@@ -91,6 +121,7 @@ jobs:
                   key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
                   restore-keys: |
                       ${{ runner.os }}-yarn-cache-node-modules-
+
             - name: Yarn install
               if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
               run: yarn install
@@ -100,3 +131,5 @@ jobs:
 
             - name: Execute tests via PHPUnit
               run: vendor/bin/phpunit
+              env:
+                  DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
